setTimeout('ctl00_IWS_WH_CPH_Content_SlideshowControl1 = new iws.SlideShowControl(\'ctl00_IWS_WH_CPH_Content_SlideshowControl1\',
 \'en-US\', \'\', 5, 1, 0, 
 \'./our_gift_item_gallery_files/1986a.JPG\' , \'1986--The \\u201CDR. SHAPIRO KEEPS ME SMILING\\u201D refrigerator tooth magnet\',
 \'./our_gift_item_gallery_files/1987.JPG\' , \'1987--Emergency Telephone Number magnet\', \'./our_gift_item_gallery_files/1988.JPG\' , 
 \'1988--The \\u201CTEETH SO CLEAN YOU CAN EAT OFF OF \\u2018EM\\u201D expanding tooth sponge\', \'./our_gift_item_gallery_files/1989.JPG\' , 
 \'1989--The \\u201CPut Your Mouth In Our Hands, An We\\u2019ll Put Our Hands In Your Mouth\\u201D jar opener\', 
 \'./our_gift_item_gallery_files/1990.JPG\' , \'1990--The \\u201CFOR A GOOD TIME CALL\\u2014DOCTOR SHAPIRO\\u201D magneticly closing address book\', 
 \'./our_gift_item_gallery_files/1991.JPG\' , \'1991--The \\u201DAlways on the Cutting Edge\\u201D letter opener\',  
 \'./our_gift_item_gallery_files/1992.JPG\' , \'1992--The \\u201CTEETH FILLED WHILE-U-WAIT\\u201D coffee mug\',
 \'./our_gift_item_gallery_files/1993.jpg\' , \'1993--The \\u201CDr. Shapiro \\u2018Ask for Him by Name\\u2019\\u201D erasable note board, emergency number and health emergency chart\', 
 \'./our_gift_item_gallery_files/1994.JPG\' , \'1994--The \\u201CDr. Shapiro Puts the treat back in dental treatment\\u201D chip bag clip\', 
 \'./our_gift_item_gallery_files/1995.JPG\' , \'1995--The \\u201CDr. Shapiro\\u2019s \\u201CWhere you won\\u2019t get\\u2026..taken\\u2019\\u201D double ended pocket screwdriver\', 
 \'./our_gift_item_gallery_files/1996.jpg\' , \'1996--The \\u201CHe gets in your face!\\u201D folding hand mirror\', 
 \'./our_gift_item_gallery_files/1997.jpg\' , \'1997--The \\u201CHE SUPPORTS YOUR RIGHT TO CHEWS!\\u201D pizza cutter and server\', 
 \'./our_gift_item_gallery_files/1998.JPG\' , \'1998--The \\u201CCompliments of\\u2026Doc Shapiro\\u2019s Filling Station!\\u201D ice scraper and gas nozzle lock\', 
 \'./our_gift_item_gallery_files/1999.JPG\' , \'1999--The \\u201CStick it in your Mouth\\u201D lighted home oral exam mirror\', 
 \'./our_gift_item_gallery_files/2000.JPG\' , \'2000--The \\u201CDr. Shapiro\\u2019s:  The Second Best Thing You Can Do With Your Mouth!\\u201D water bottle\', 
 \'./our_gift_item_gallery_files/2001.JPG\' , \'2001--The \\u201CShapiro: The Next Millennium!  Just when you thought it was safe\\u2026to stop brushing\\u201D folding lint brush and shoe horn\', 
 \'./our_gift_item_gallery_files/2002.JPG\' , \'2002--The \\u201CHold Me!  Squeeze Me!  Floss Me!\\u201D tooth shaped stress reducer\',
 \'./our_gift_item_gallery_files/2003.JPG\' , \'2003--The \\u201CI\\u2019m A Shapiro Fan\\u201D portable fan\', 
 \'./our_gift_item_gallery_files/2004.JPG\' , \'2004--The \\u201CShapiro Rules\\u201D pocket tape measure and level\',
 \'./our_gift_item_gallery_files/2005.jpg\' , \'2005--The \\u201CFrom Dr. Shapiro, It Figures\\u201D hand calculator \',
 \'./our_gift_item_gallery_files/2006.JPG\' , \'2006--The \\u201COpen! Open! Open! Open!\\u201D  4-way beverage opener\', 
 \'./our_gift_item_gallery_files/2007.JPG\' , \'2007--The \\\"Dr. Shapiro: Saving The Planet One Tooth At A Time\\\" spinning squeeze globe pen\',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2008--The \\\"Cavities Fear Him\\\" security whistle, flashlight, keychain\',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2009--The \\\"THE DOCTOR SHAPIRO DENTAL BACKPACK   Instructions: Open Wide, Then Fill   (things are better in the sack on your back)\\\" backpack tote\',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2010--The \\\"The “Your Teeth: Great With Food”\\\" 4-in-1 measuring spoon set\',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2011--The \\\"The “ALL SPIT & POLISH”\\\" pocket travel shoe shine kit\',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2012--The \\\"The “Get The Scoop At Dr. Shapiro's”\\\" ice cream scoop \',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2013--The \\\"he “Put Your Mouth In Our Hands, And We’ll Put Our Hands In Your Mouth!”\\\"  combo back scratcher shoe horn\',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2014--The \\\"The “4 ur App @ Dr S.  cl: ”  \\\" cell phone stand and screen cleaner\',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2015--The \\\"The “THREAD! It's like floss for your clothes” \\\" travel emergency sewing kit\',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2016--The \\\"The “DR. SHAPIRO: MOUTH TESTED, TEETH APPROVED!” \\\" compact pocket utensil kit (fork knife spoon tongs)\',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2017--The \\\"The “Comb? Teeth?   Brush? Teeth?   Get it?  Dentist? Teeth?   Comb? Brush? Teeth?”  \\\" folding comb ad hairbrush \',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2018--The \\\"The “Shapiro My Hero” emergency car escape tool  \\\" seat belt cutter, window breaker, help whistle\',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2019--The \\\"The “DR. SHAPIRO, THE WRITE STUFF” \\\" seven-in-one combo pen\',
 \'./our_gift_item_gallery_files/2008.jpg\' , \'2020--The \\\"The \\u201CDr Shapiro Cares For Choppers\\u201D\\\" multifunctional cutting board (cut rinse store pour)\',
 );', 150);